import React from 'react';
import { BellIcon, CheckCircle2Icon, Clock3Icon, PlusIcon, WrenchIcon } from 'lucide-react';
import { Button, Card } from '../components/ui/primitives';
import { useApp } from '../context/AppContext';

const reminders = [
  { id: 'brake', title: 'Brake Pad Replacement', vehicle: 'Tesla Model 3', detail: 'Daily Driver', due: 'Jul 15, 2026', note: 'Overdue by 4 days', cost: '$280.00', progress: 94, tone: 'urgent' },
  { id: 'oil', title: 'Oil & Filter Change', vehicle: 'Toyota RAV4', detail: 'Weekend SUV', due: 'Jul 28, 2026', note: 'Due in 12 days', cost: '$85.00', progress: 82, tone: 'soon' },
  { id: 'tire', title: 'Tire Rotation', vehicle: 'Ford F-150', detail: 'Work Truck', due: 'Aug 12, 2026', note: 'Due in 28 days', cost: '$45.00', progress: 68, tone: 'upcoming' },
  { id: 'registration', title: 'Annual Vehicle Registration', vehicle: 'Tesla Model 3', detail: 'Daily Driver', due: 'Aug 29, 2026', note: 'Due in 45 days', cost: '$180.00', progress: 42, tone: 'upcoming' },
];

function ReminderCard({ reminder, onSchedule }: { reminder: typeof reminders[number]; onSchedule: () => void }) {
  const badge = reminder.tone === 'urgent' ? 'bg-red-50 text-red-500 border-red-200' : reminder.tone === 'soon' ? 'bg-amber-50 text-amber-600 border-amber-200' : 'bg-indigo-50 text-indigo-600 border-indigo-200';
  const label = reminder.tone === 'urgent' ? 'Urgent' : reminder.tone === 'soon' ? 'Due Soon' : 'Upcoming';
  const mileage = reminder.id === 'registration' ? '—' : reminder.id === 'tire' ? '102,500 mi' : reminder.id === 'oil' ? '69,000 mi' : '34,500 mi';
  return <Card className="p-4 sm:p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 text-slate-500"><WrenchIcon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{reminder.title}</h3><p className="text-xs text-slate-500">{reminder.vehicle} • {reminder.detail}</p></div><span className={`rounded-md border px-2 py-1 text-[11px] font-medium ${badge}`}>{label}</span></div><div className="mt-5 grid grid-cols-2 gap-4 text-xs"><div><p className="text-slate-500">Due date</p><p className="font-semibold">{reminder.due}</p><p className="text-slate-500">{reminder.note}</p></div><div><p className="text-slate-500">Est. cost</p><p className="font-semibold">{reminder.cost}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div><p className="mb-1 text-slate-500">Service mileage</p><p className="font-semibold">{mileage}</p></div><div><p className="mb-1 text-slate-500">Progress</p><div className="mt-2 h-1.5 rounded-full bg-indigo-100"><div className="h-1.5 rounded-full bg-indigo-600" style={{ width: `${reminder.progress}%` }} /></div></div></div><div className="mt-4 grid grid-cols-2 gap-2"><Button onClick={onSchedule}>Schedule</Button><Button variant="secondary">Mark Done</Button></div></div></div></Card>;
}

export function Reminders() {
  const { toast } = useApp();
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-[25px] font-semibold tracking-tight">Maintenance Reminders</h1><p className="mt-1 text-sm text-slate-500">Stay ahead of service dates, recurring tasks, and vehicle registration deadlines.</p></div><Button onClick={() => toast('Reminder created (demo)')}><PlusIcon className="h-4 w-4" /> Add Reminder</Button></div><div className="grid gap-4 md:grid-cols-3"><Card className="flex items-center gap-3 p-5"><span className="rounded-full bg-red-50 p-3 text-red-500"><BellIcon className="h-5 w-5" /></span><div><p className="text-2xl font-semibold">1</p><p className="text-xs text-slate-500">Overdue reminder</p></div></Card><Card className="flex items-center gap-3 p-5"><span className="rounded-full bg-amber-50 p-3 text-amber-500"><Clock3Icon className="h-5 w-5" /></span><div><p className="text-2xl font-semibold">1</p><p className="text-xs text-slate-500">Due this month</p></div></Card><Card className="flex items-center gap-3 p-5"><span className="rounded-full bg-indigo-50 p-3 text-indigo-600"><CheckCircle2Icon className="h-5 w-5" /></span><div><p className="text-2xl font-semibold">2</p><p className="text-xs text-slate-500">Completed this month</p></div></Card></div><div className="grid gap-5 lg:grid-cols-2">{reminders.map((reminder) => <ReminderCard key={reminder.id} reminder={reminder} onSchedule={() => toast(`Scheduling ${reminder.title} (demo)`)} />)}</div><Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 font-semibold">Completed This Month</div><div className="divide-y divide-slate-100">{['Wiper Blade Replacement', 'Air Filter Change'].map((item, index) => <div key={item} className="flex items-center gap-3 px-5 py-4"><CheckCircle2Icon className="h-5 w-5 text-emerald-500" /><div><p className="font-medium">{item}</p><p className="text-xs text-slate-500">{index ? 'Ford F-150 • Jul 05, 2026' : 'Toyota RAV4 • Jul 02, 2026'}</p></div><span className="ml-auto text-sm font-medium">{index ? '$28.50' : '$32.00'}</span></div>)}</div></Card></div>;
}